### ISSUE TITLE
Datebase is Locked

### ISSUE THREAD

**Issue by kpfromer** [nheinric/addToAnki#2]
I am getting this error when I run `./add_to_anki-2.0.12.py /Users/kpfromer/Documents/Anki/User\ 1/collection.anki2 Spanish hello das`
Error:
`Traceback (most recent call last):
  File "./add_to_anki-2.0.12.py", line 21, in <module>
    deck = aopen( coll_file );
  File "anki/storage.pyc", line 51, in Collection
  File "anki/collection.pyc", line 144, in lock
  File "anki/db.pyc", line 43, in execute
sqlite3.OperationalError: database is locked
`

**Comment by hwchiu** [comment]
You need to close the anki application first.
